// request_get_preset_status.proto/Open GoPro, Version 2.0 (C) Copyright 2021 GoPro, Inc. (http://gopro.com/OpenGoPro).

// This copyright was auto-generated on Wed Jul  5 19:32:05 UTC 2023

//
//Defines the structure of protobuf messages for obtaining preset status

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: request_get_preset_status.proto

package open_gopro

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumRegisterPresetStatus int32

const (
	EnumRegisterPresetStatus_REGISTER_PRESET_STATUS_PRESET             EnumRegisterPresetStatus = 1 // Send notification when properties of a preset change
	EnumRegisterPresetStatus_REGISTER_PRESET_STATUS_PRESET_GROUP_ARRAY EnumRegisterPresetStatus = 2 // Send notification when properties of a preset group change
)

// Enum value maps for EnumRegisterPresetStatus.
var (
	EnumRegisterPresetStatus_name = map[int32]string{
		1: "REGISTER_PRESET_STATUS_PRESET",
		2: "REGISTER_PRESET_STATUS_PRESET_GROUP_ARRAY",
	}
	EnumRegisterPresetStatus_value = map[string]int32{
		"REGISTER_PRESET_STATUS_PRESET":             1,
		"REGISTER_PRESET_STATUS_PRESET_GROUP_ARRAY": 2,
	}
)

func (x EnumRegisterPresetStatus) Enum() *EnumRegisterPresetStatus {
	p := new(EnumRegisterPresetStatus)
	*p = x
	return p
}

func (x EnumRegisterPresetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumRegisterPresetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_request_get_preset_status_proto_enumTypes[0].Descriptor()
}

func (EnumRegisterPresetStatus) Type() protoreflect.EnumType {
	return &file_request_get_preset_status_proto_enumTypes[0]
}

func (x EnumRegisterPresetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EnumRegisterPresetStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EnumRegisterPresetStatus(num)
	return nil
}

// Deprecated: Use EnumRegisterPresetStatus.Descriptor instead.
func (EnumRegisterPresetStatus) EnumDescriptor() ([]byte, []int) {
	return file_request_get_preset_status_proto_rawDescGZIP(), []int{0}
}

type RequestGetPresetStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegisterPresetStatus   []EnumRegisterPresetStatus `protobuf:"varint,1,rep,name=register_preset_status,json=registerPresetStatus,enum=open_gopro.EnumRegisterPresetStatus" json:"register_preset_status,omitempty"`       // Array of Preset statuses to be notified about
	UnregisterPresetStatus []EnumRegisterPresetStatus `protobuf:"varint,2,rep,name=unregister_preset_status,json=unregisterPresetStatus,enum=open_gopro.EnumRegisterPresetStatus" json:"unregister_preset_status,omitempty"` // Array of Preset statuses to stop being notified about
}

func (x *RequestGetPresetStatus) Reset() {
	*x = RequestGetPresetStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_request_get_preset_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGetPresetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetPresetStatus) ProtoMessage() {}

func (x *RequestGetPresetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_request_get_preset_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetPresetStatus.ProtoReflect.Descriptor instead.
func (*RequestGetPresetStatus) Descriptor() ([]byte, []int) {
	return file_request_get_preset_status_proto_rawDescGZIP(), []int{0}
}

func (x *RequestGetPresetStatus) GetRegisterPresetStatus() []EnumRegisterPresetStatus {
	if x != nil {
		return x.RegisterPresetStatus
	}
	return nil
}

func (x *RequestGetPresetStatus) GetUnregisterPresetStatus() []EnumRegisterPresetStatus {
	if x != nil {
		return x.UnregisterPresetStatus
	}
	return nil
}

var File_request_get_preset_status_proto protoreflect.FileDescriptor

var file_request_get_preset_status_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x70, 0x72,
	0x65, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x22, 0xd4, 0x01,
	0x0a, 0x16, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x50, 0x72, 0x65, 0x73,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x5a, 0x0a, 0x16, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x5f,
	0x67, 0x6f, 0x70, 0x72, 0x6f, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x14,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x5e, 0x0a, 0x18, 0x75, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x5f, 0x70, 0x72, 0x65, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x67, 0x6f,
	0x70, 0x72, 0x6f, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x16, 0x75, 0x6e,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x2a, 0x6c, 0x0a, 0x18, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x21, 0x0a, 0x1d, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x50, 0x52, 0x45,
	0x53, 0x45, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x52, 0x45, 0x53, 0x45,
	0x54, 0x10, 0x01, 0x12, 0x2d, 0x0a, 0x29, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x5f,
	0x50, 0x52, 0x45, 0x53, 0x45, 0x54, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x52,
	0x45, 0x53, 0x45, 0x54, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x5f, 0x41, 0x52, 0x52, 0x41, 0x59,
	0x10, 0x02, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x75, 0x61, 0x70, 0x61, 0x70, 0x61, 0x2f, 0x67, 0x6f, 0x5f, 0x67, 0x6f, 0x70, 0x72,
	0x6f, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x67, 0x6f, 0x70, 0x72, 0x6f,
}

var (
	file_request_get_preset_status_proto_rawDescOnce sync.Once
	file_request_get_preset_status_proto_rawDescData = file_request_get_preset_status_proto_rawDesc
)

func file_request_get_preset_status_proto_rawDescGZIP() []byte {
	file_request_get_preset_status_proto_rawDescOnce.Do(func() {
		file_request_get_preset_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_request_get_preset_status_proto_rawDescData)
	})
	return file_request_get_preset_status_proto_rawDescData
}

var file_request_get_preset_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_request_get_preset_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_get_preset_status_proto_goTypes = []interface{}{
	(EnumRegisterPresetStatus)(0),  // 0: open_gopro.EnumRegisterPresetStatus
	(*RequestGetPresetStatus)(nil), // 1: open_gopro.RequestGetPresetStatus
}
var file_request_get_preset_status_proto_depIdxs = []int32{
	0, // 0: open_gopro.RequestGetPresetStatus.register_preset_status:type_name -> open_gopro.EnumRegisterPresetStatus
	0, // 1: open_gopro.RequestGetPresetStatus.unregister_preset_status:type_name -> open_gopro.EnumRegisterPresetStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_request_get_preset_status_proto_init() }
func file_request_get_preset_status_proto_init() {
	if File_request_get_preset_status_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_request_get_preset_status_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGetPresetStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_request_get_preset_status_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_get_preset_status_proto_goTypes,
		DependencyIndexes: file_request_get_preset_status_proto_depIdxs,
		EnumInfos:         file_request_get_preset_status_proto_enumTypes,
		MessageInfos:      file_request_get_preset_status_proto_msgTypes,
	}.Build()
	File_request_get_preset_status_proto = out.File
	file_request_get_preset_status_proto_rawDesc = nil
	file_request_get_preset_status_proto_goTypes = nil
	file_request_get_preset_status_proto_depIdxs = nil
}
