// response_generic.proto/Open GoPro, Version 2.0 (C) Copyright 2021 GoPro, Inc. (http://gopro.com/OpenGoPro).

// This copyright was auto-generated on Fri Jun  9 22:49:36 UTC 2023

//
//Defines the structure of protobuf message containing generic response to a command

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: response_generic.proto

package open_gopro

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumResultGeneric int32

const (
	EnumResultGeneric_RESULT_UNKNOWN                EnumResultGeneric = 0
	EnumResultGeneric_RESULT_SUCCESS                EnumResultGeneric = 1
	EnumResultGeneric_RESULT_ILL_FORMED             EnumResultGeneric = 2
	EnumResultGeneric_RESULT_NOT_SUPPORTED          EnumResultGeneric = 3
	EnumResultGeneric_RESULT_ARGUMENT_OUT_OF_BOUNDS EnumResultGeneric = 4
	EnumResultGeneric_RESULT_ARGUMENT_INVALID       EnumResultGeneric = 5
)

// Enum value maps for EnumResultGeneric.
var (
	EnumResultGeneric_name = map[int32]string{
		0: "RESULT_UNKNOWN",
		1: "RESULT_SUCCESS",
		2: "RESULT_ILL_FORMED",
		3: "RESULT_NOT_SUPPORTED",
		4: "RESULT_ARGUMENT_OUT_OF_BOUNDS",
		5: "RESULT_ARGUMENT_INVALID",
	}
	EnumResultGeneric_value = map[string]int32{
		"RESULT_UNKNOWN":                0,
		"RESULT_SUCCESS":                1,
		"RESULT_ILL_FORMED":             2,
		"RESULT_NOT_SUPPORTED":          3,
		"RESULT_ARGUMENT_OUT_OF_BOUNDS": 4,
		"RESULT_ARGUMENT_INVALID":       5,
	}
)

func (x EnumResultGeneric) Enum() *EnumResultGeneric {
	p := new(EnumResultGeneric)
	*p = x
	return p
}

func (x EnumResultGeneric) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumResultGeneric) Descriptor() protoreflect.EnumDescriptor {
	return file_response_generic_proto_enumTypes[0].Descriptor()
}

func (EnumResultGeneric) Type() protoreflect.EnumType {
	return &file_response_generic_proto_enumTypes[0]
}

func (x EnumResultGeneric) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EnumResultGeneric) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EnumResultGeneric(num)
	return nil
}

// Deprecated: Use EnumResultGeneric.Descriptor instead.
func (EnumResultGeneric) EnumDescriptor() ([]byte, []int) {
	return file_response_generic_proto_rawDescGZIP(), []int{0}
}

type ResponseGeneric struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *EnumResultGeneric `protobuf:"varint,1,req,name=result,enum=open_gopro.EnumResultGeneric" json:"result,omitempty"` // Generic pass/fail/error info
}

func (x *ResponseGeneric) Reset() {
	*x = ResponseGeneric{}
	if protoimpl.UnsafeEnabled {
		mi := &file_response_generic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGeneric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGeneric) ProtoMessage() {}

func (x *ResponseGeneric) ProtoReflect() protoreflect.Message {
	mi := &file_response_generic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGeneric.ProtoReflect.Descriptor instead.
func (*ResponseGeneric) Descriptor() ([]byte, []int) {
	return file_response_generic_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseGeneric) GetResult() EnumResultGeneric {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return EnumResultGeneric_RESULT_UNKNOWN
}

var File_response_generic_proto protoreflect.FileDescriptor

var file_response_generic_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72,
	0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x67,
	0x6f, 0x70, 0x72, 0x6f, 0x22, 0x48, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x12, 0x35, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x67,
	0x6f, 0x70, 0x72, 0x6f, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0xac,
	0x01, 0x0a, 0x11, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x53, 0x55,
	0x4c, 0x54, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11,
	0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x49, 0x4c, 0x4c, 0x5f, 0x46, 0x4f, 0x52, 0x4d, 0x45,
	0x44, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x4e, 0x4f,
	0x54, 0x5f, 0x53, 0x55, 0x50, 0x50, 0x4f, 0x52, 0x54, 0x45, 0x44, 0x10, 0x03, 0x12, 0x21, 0x0a,
	0x1d, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x41, 0x52, 0x47, 0x55, 0x4d, 0x45, 0x4e, 0x54,
	0x5f, 0x4f, 0x55, 0x54, 0x5f, 0x4f, 0x46, 0x5f, 0x42, 0x4f, 0x55, 0x4e, 0x44, 0x53, 0x10, 0x04,
	0x12, 0x1b, 0x0a, 0x17, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x41, 0x52, 0x47, 0x55, 0x4d,
	0x45, 0x4e, 0x54, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x05, 0x42, 0x28, 0x5a,
	0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x75, 0x61, 0x70,
	0x61, 0x70, 0x61, 0x2f, 0x67, 0x6f, 0x5f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x2f, 0x6f, 0x70, 0x65,
	0x6e, 0x5f, 0x67, 0x6f, 0x70, 0x72, 0x6f,
}

var (
	file_response_generic_proto_rawDescOnce sync.Once
	file_response_generic_proto_rawDescData = file_response_generic_proto_rawDesc
)

func file_response_generic_proto_rawDescGZIP() []byte {
	file_response_generic_proto_rawDescOnce.Do(func() {
		file_response_generic_proto_rawDescData = protoimpl.X.CompressGZIP(file_response_generic_proto_rawDescData)
	})
	return file_response_generic_proto_rawDescData
}

var file_response_generic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_response_generic_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_response_generic_proto_goTypes = []interface{}{
	(EnumResultGeneric)(0),  // 0: open_gopro.EnumResultGeneric
	(*ResponseGeneric)(nil), // 1: open_gopro.ResponseGeneric
}
var file_response_generic_proto_depIdxs = []int32{
	0, // 0: open_gopro.ResponseGeneric.result:type_name -> open_gopro.EnumResultGeneric
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_response_generic_proto_init() }
func file_response_generic_proto_init() {
	if File_response_generic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_response_generic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGeneric); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_response_generic_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_generic_proto_goTypes,
		DependencyIndexes: file_response_generic_proto_depIdxs,
		EnumInfos:         file_response_generic_proto_enumTypes,
		MessageInfos:      file_response_generic_proto_msgTypes,
	}.Build()
	File_response_generic_proto = out.File
	file_response_generic_proto_rawDesc = nil
	file_response_generic_proto_goTypes = nil
	file_response_generic_proto_depIdxs = nil
}
