// set_camera_control_status.proto/Open GoPro, Version 2.0 (C) Copyright 2021 GoPro, Inc. (http://gopro.com/OpenGoPro).

// This copyright was auto-generated on Fri Jun  9 22:49:36 UTC 2023

//
//Defines the structure of protobuf messages for setting camera control status

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: set_camera_control_status.proto

package open_gopro

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumCameraControlStatus int32

const (
	EnumCameraControlStatus_CAMERA_IDLE             EnumCameraControlStatus = 0
	EnumCameraControlStatus_CAMERA_CONTROL          EnumCameraControlStatus = 1 // Can only be set by camera, not by third-party
	EnumCameraControlStatus_CAMERA_EXTERNAL_CONTROL EnumCameraControlStatus = 2
)

// Enum value maps for EnumCameraControlStatus.
var (
	EnumCameraControlStatus_name = map[int32]string{
		0: "CAMERA_IDLE",
		1: "CAMERA_CONTROL",
		2: "CAMERA_EXTERNAL_CONTROL",
	}
	EnumCameraControlStatus_value = map[string]int32{
		"CAMERA_IDLE":             0,
		"CAMERA_CONTROL":          1,
		"CAMERA_EXTERNAL_CONTROL": 2,
	}
)

func (x EnumCameraControlStatus) Enum() *EnumCameraControlStatus {
	p := new(EnumCameraControlStatus)
	*p = x
	return p
}

func (x EnumCameraControlStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumCameraControlStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_set_camera_control_status_proto_enumTypes[0].Descriptor()
}

func (EnumCameraControlStatus) Type() protoreflect.EnumType {
	return &file_set_camera_control_status_proto_enumTypes[0]
}

func (x EnumCameraControlStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EnumCameraControlStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EnumCameraControlStatus(num)
	return nil
}

// Deprecated: Use EnumCameraControlStatus.Descriptor instead.
func (EnumCameraControlStatus) EnumDescriptor() ([]byte, []int) {
	return file_set_camera_control_status_proto_rawDescGZIP(), []int{0}
}

type RequestSetCameraControlStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CameraControlStatus *EnumCameraControlStatus `protobuf:"varint,1,req,name=camera_control_status,json=cameraControlStatus,enum=open_gopro.EnumCameraControlStatus" json:"camera_control_status,omitempty"` // Declare who is taking control of the camera
}

func (x *RequestSetCameraControlStatus) Reset() {
	*x = RequestSetCameraControlStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_camera_control_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestSetCameraControlStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSetCameraControlStatus) ProtoMessage() {}

func (x *RequestSetCameraControlStatus) ProtoReflect() protoreflect.Message {
	mi := &file_set_camera_control_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSetCameraControlStatus.ProtoReflect.Descriptor instead.
func (*RequestSetCameraControlStatus) Descriptor() ([]byte, []int) {
	return file_set_camera_control_status_proto_rawDescGZIP(), []int{0}
}

func (x *RequestSetCameraControlStatus) GetCameraControlStatus() EnumCameraControlStatus {
	if x != nil && x.CameraControlStatus != nil {
		return *x.CameraControlStatus
	}
	return EnumCameraControlStatus_CAMERA_IDLE
}

var File_set_camera_control_status_proto protoreflect.FileDescriptor

var file_set_camera_control_status_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x73, 0x65, 0x74, 0x5f, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x5f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x22, 0x78, 0x0a,
	0x1d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x65, 0x72,
	0x61, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x57,
	0x0a, 0x15, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x23, 0x2e,
	0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x43,
	0x61, 0x6d, 0x65, 0x72, 0x61, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x13, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x5b, 0x0a, 0x17, 0x45, 0x6e, 0x75, 0x6d, 0x43,
	0x61, 0x6d, 0x65, 0x72, 0x61, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x41, 0x4d, 0x45, 0x52, 0x41, 0x5f, 0x49, 0x44, 0x4c,
	0x45, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x41, 0x4d, 0x45, 0x52, 0x41, 0x5f, 0x43, 0x4f,
	0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x41, 0x4d, 0x45, 0x52,
	0x41, 0x5f, 0x45, 0x58, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x52,
	0x4f, 0x4c, 0x10, 0x02, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x75, 0x61, 0x70, 0x61, 0x70, 0x61, 0x2f, 0x67, 0x6f, 0x5f, 0x67, 0x6f,
	0x70, 0x72, 0x6f, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x67, 0x6f, 0x70, 0x72, 0x6f,
}

var (
	file_set_camera_control_status_proto_rawDescOnce sync.Once
	file_set_camera_control_status_proto_rawDescData = file_set_camera_control_status_proto_rawDesc
)

func file_set_camera_control_status_proto_rawDescGZIP() []byte {
	file_set_camera_control_status_proto_rawDescOnce.Do(func() {
		file_set_camera_control_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_set_camera_control_status_proto_rawDescData)
	})
	return file_set_camera_control_status_proto_rawDescData
}

var file_set_camera_control_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_set_camera_control_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_set_camera_control_status_proto_goTypes = []interface{}{
	(EnumCameraControlStatus)(0),          // 0: open_gopro.EnumCameraControlStatus
	(*RequestSetCameraControlStatus)(nil), // 1: open_gopro.RequestSetCameraControlStatus
}
var file_set_camera_control_status_proto_depIdxs = []int32{
	0, // 0: open_gopro.RequestSetCameraControlStatus.camera_control_status:type_name -> open_gopro.EnumCameraControlStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_set_camera_control_status_proto_init() }
func file_set_camera_control_status_proto_init() {
	if File_set_camera_control_status_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_set_camera_control_status_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestSetCameraControlStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_set_camera_control_status_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_set_camera_control_status_proto_goTypes,
		DependencyIndexes: file_set_camera_control_status_proto_depIdxs,
		EnumInfos:         file_set_camera_control_status_proto_enumTypes,
		MessageInfos:      file_set_camera_control_status_proto_msgTypes,
	}.Build()
	File_set_camera_control_status_proto = out.File
	file_set_camera_control_status_proto_rawDesc = nil
	file_set_camera_control_status_proto_goTypes = nil
	file_set_camera_control_status_proto_depIdxs = nil
}
